[default]
extend-ignore-identifiers-re = [
    "datas", "Datas", "inh", "nd", "lok",
    "sur", "leasure", "asure", "nulll", "finf",
    "iy", "ERROR_FILENAME_EXCED_RANGE", "FLE",
    "nam", "ND", "eisDST"
]
