name: "Bug report"
description: "Create a report to help us improve"
title: "[BUG] <description>"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes: 
      label: Description
      description: Provide a general summary of the bug you found
    validations:
      required: true
  - type: textarea
    id: expectedbhv
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: currentbhv
    attributes:
      label: Current behavior
      description: Tell us what happens instead
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: true
