name: Build [Clang] - macOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Panquesito7/setup-jule@v1.1.3
        with:
          version: dev
          directory: .
          add-to-path: true

      - name: Build JuleC
        run: |
          julec --compiler clang src/julec
