name: Build - C++14
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Build JuleC
        run: |
          julec --compiler clang --cppstd cpp14 src/julec
