name: Build (Linux)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Panquesito7/setup-jule@v1.1.2
        with:
          version: dev
          directory: .
          add-to-path: true

      - name: Build JuleC
        run: |
          julec -t ./src/julec
          clang++ -O0 --std=c++17 -Wno-everything ./dist/ir.cpp
