name: Std Tests [GCC] - macOS
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - std::encoding::ascii85
        run: |
          julec test --compiler gcc --compiler-path g++-13 -o test std/encoding/ascii85
          ./test

      - name: Test - std::math::big
        run: |
          julec test --compiler gcc --compiler-path g++-13 -o test std/math/big
          ./test
