name: Std Tests [GCC] - macOS
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - std::encoding::ascii85
        run: |
          julec test --compiler gcc --compiler-path g++-13 -o test -t std/encoding/ascii85
          g++-13 -w --std=c++17 -O0 -Wl,-ld_classic -o test dist/ir.cpp
          ./test

      - name: Test - std::math::big
        run: |
          julec test --compiler gcc --compiler-path g++-13 -o test -t std/math/big
          g++-13 -w --std=c++17 -O0 -Wl,-ld_classic -o test dist/ir.cpp
          ./test

      - name: Test - std::slices
        run: |
          julec test --compiler gcc --compiler-path g++-13 -o test -t std/math/slices
          g++-13 -w --std=c++17 -O0 -Wl,-ld_classic -o test dist/ir.cpp
          ./test
