name: Std Tests [Clang] - Ubuntu
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - std::math::big
        run: |
          julec test --compiler clang -o test std/math/big
          ./test
