name: Std Tests [GCC] - macOS
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Panquesito7/setup-jule@v1.1.3
        with:
          version: dev
          directory: .
          add-to-path: true

      - name: Test - std::math::big
        run: |
          julec test -t --compiler gcc -o test std/math/big
          g++-13 -w --std=c++17 dist/ir.cpp -o test
          ./test
