name: Std Tests [GCC] - Ubuntu
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - std/bufio
        run: |
          julec test --compiler gcc -o test std/bufio
          ./test

      - name: Test - std/internal/byteslite
        run: |
          julec test --compiler gcc -o test std/internal/byteslite
          ./test

      - name: Test - std/internal/conv
        run: |
          julec test --compiler gcc -o test std/internal/conv
          ./test

      - name: Test - std/encoding/ascii85
        run: |
          julec test --compiler gcc -o test std/encoding/ascii85
          ./test

      - name: Test - std/encoding/base32
        run: |
          julec test --compiler gcc -o test std/encoding/base32
          ./test

      - name: Test - std/encoding/base64
        run: |
          julec test --compiler gcc -o test std/encoding/base64
          ./test

      - name: Test - std/encoding/json
        run: |
          julec test --compiler gcc -o test std/encoding/json
          ./test

      - name: Test - std/hash/adler32
        run: |
          julec test --compiler gcc -o test std/hash/adler32
          ./test

      - name: Test - std/hash/fnv
        run: |
          julec test --compiler gcc -o test std/hash/fnv
          ./test

      - name: Test - std/maps
        run: |
          julec test --compiler gcc -o test std/maps
          ./test

      - name: Test - std/math/big
        run: |
          julec test --compiler gcc -o test std/math/big
          ./test

      - name: Test - std/math/cmplx
        run: |
          julec test --compiler gcc -o test std/math/cmplx
          ./test

      - name: Test - std/net
        run: |
          julec test --compiler gcc -o test std/net
          ./test

      - name: Test - std/slices
        run: |
          julec test --compiler gcc -o test std/slices
          ./test

      - name: Test - std/time
        run: |
          julec test --compiler gcc -o test std/time
          ./test

      - name: Test - std/unicode/utf8
        run: |
          julec test --compiler gcc -o test std/unicode/utf8/test
          ./test

      - name: Test - std/unicode/utf16
        run: |
          julec test --compiler gcc -o test std/unicode/utf16/test
          ./test